[package]
name = "eddsa"
version = "2.0.2"
description = "A library for EdDSA public keys/signatures in Motoko"
repository = "https://github.com/edjcase/motoko_eddsa"
keywords = [
  "eddsa",
  "signature",
  "verify",
  "key",
  "public",
  "private",
  "curve",
  "cryptography"
]
license = "MIT"

[dependencies]
core = "0.6.0"
base-x-encoder = "2.0.0"
asn1 = "3.0.1"
sha2 = "0.1.6"
tweetnacl = "1.1.2"
buffer = "0.0.1"
xtended-iter = "1.0.0"

[dev-dependencies]
test = "2.1.1"
bench = "1.0.0"

[toolchain]
moc = "0.14.14"
